const mockData = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@mailworld.com",
    date: "12/11/2024",
    time: "9:30am",
    status: "Completed",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@fastmail.co.uk",
    date: "03/12/2024",
    time: "10:45am",
    status: "Pending",
  },
  {
    id: 3,
    name: "Charlie Brown",
    email: "charlie.brown@webpost.net",
    date: "15/12/2024",
    time: "11:20am",
    status: "Pending",
  },
  {
    id: 4,
    name: "Diana Prince",
    email: "diana.prince@worldmail.com",
    date: "23/09/2024",
    time: "3:05pm",
    status: "Completed",
  },
  {
    id: 5,
    name: "Ethan Hunt",
    email: "ethan.hunt@securemail.io",
    date: "19/12/2024",
    time: "4:20pm",
    status: "Pending",
  },
  {
    id: 6,
    name: "Fiona Gallagher",
    email: "fiona.g@zoopmail.org",
    date: "04/04/2025",
    time: "9:45am",
    status: "Pending",
  },
  {
    id: 7,
    name: "George Michaels",
    email: "george.michaels@lightpost.co",
    date: "17/06/2025",
    time: "10:10am",
    status: "Pending",
  },
  {
    id: 8,
    name: "Hannah Wright",
    email: "hannah.wright@fastlane.net",
    date: "12/10/2024",
    time: "11:50am",
    status: "Completed",
  },
  {
    id: 9,
    name: "Ian Black",
    email: "ian.black@mailhero.com",
    date: "28/08/2025",
    time: "12:25pm",
    status: "Cancelled",
  },
  {
    id: 10,
    name: "Jessica Jones",
    email: "jessica.jones@zapmail.net",
    date: "15/12/2024",
    time: "1:05pm",
    status: "Pending",
  },
  {
    id: 11,
    name: "Kevin Arnold",
    email: "kevin.arnold@onestopmail.com",
    date: "10/09/2024",
    time: "1:30pm",
    status: "Completed",
  },
  {
    id: 12,
    name: "Laura Hill",
    email: "laura.hill@quickmail.co.uk",
    date: "23/03/2025",
    time: "3:15pm",
    status: "Cancelled",
  },
  {
    id: 13,
    name: "Michael Scott",
    email: "m.scott@paperworld.com",
    date: "08/12/2024",
    time: "2:10pm",
    status: "Pending",
  },
  {
    id: 14,
    name: "Natalie Green",
    email: "n.green@mailchamp.net",
    date: "09/08/2024",
    time: "9:05am",
    status: "Completed",
  },
  {
    id: 15,
    name: "Oscar Wilde",
    email: "oscar.wilde@poetmail.com",
    date: "20/06/2025",
    time: "10:30am",
    status: "Pending",
  },
  {
    id: 16,
    name: "Paula Dean",
    email: "paula.dean@cookmail.net",
    date: "14/08/2025",
    time: "11:20am",
    status: "Pending",
  },
  {
    id: 17,
    name: "Quentin Blake",
    email: "quentin.blake@artsbox.org",
    date: "18/09/2025",
    time: "2:00pm",
    status: "Cancelled",
  },
  {
    id: 18,
    name: "Rachel Green",
    email: "r.green@bloommail.com",
    date: "27/10/2025",
    time: "2:45pm",
    status: "Pending",
  },
  {
    id: 19,
    name: "Steve Rogers",
    email: "steve.rogers@shieldmail.io",
    date: "05/12/2024",
    time: "4:10pm",
    status: "Pending",
  },
  // {
  //   id: 20,
  //   name: "Tina Turner",
  //   email: "tina.turner@starmail.net",
  //   date: "30/07/2024",
  //   time: "10:00am",
  //   status: "Completed",
  // },
  // {
  //   id: 21,
  //   name: "Uma Thurman",
  //   email: "uma.thurman@actpost.com",
  //   date: "11/03/2025",
  //   time: "12:40pm",
  //   status: "Pending",
  // },
  // {
  //   id: 22,
  //   name: "Victor Hugo",
  //   email: "victor.hugo@wordsmiths.co",
  //   date: "17/04/2025",
  //   time: "1:10pm",
  //   status: "Cancelled",
  // },
  // {
  //   id: 23,
  //   name: "Wanda Maximoff",
  //   email: "wanda.maximoff@mindmail.com",
  //   date: "06/12/2024",
  //   time: "3:50pm",
  //   status: "Pending",
  // },
  // {
  //   id: 24,
  //   name: "Xander Cage",
  //   email: "x.cage@extrememail.org",
  //   date: "19/05/2025",
  //   time: "4:30pm",
  //   status: "Pending",
  // },
  // {
  //   id: 25,
  //   name: "Yasmine Alavi",
  //   email: "yasmine.alavi@midpost.co",
  //   date: "24/07/2025",
  //   time: "10:50am",
  //   status: "Cancelled",
  // },
  // {
  //   id: 26,
  //   name: "Zane Grey",
  //   email: "zane.grey@wildmail.net",
  //   date: "13/08/2025",
  //   time: "11:35am",
  //   status: "Pending",
  // },
  // {
  //   id: 27,
  //   name: "Abby Dawson",
  //   email: "abby.dawson@quickpost.io",
  //   date: "08/09/2025",
  //   time: "1:55pm",
  //   status: "Cancelled",
  // },
  // {
  //   id: 28,
  //   name: "Barry Allen",
  //   email: "barry.allen@fastworld.co",
  //   date: "03/10/2025",
  //   time: "2:25pm",
  //   status: "Pending",
  // },
  // {
  //   id: 29,
  //   name: "Clara Oswald",
  //   email: "clara.oswald@timepost.com",
  //   date: "21/11/2025",
  //   time: "3:40pm",
  //   status: "Cancelled",
  // },
  // {
  //   id: 30,
  //   name: "David Tennant",
  //   email: "d.tennant@whomail.org",
  //   date: "31/12/2025",
  //   time: "4:55pm",
  //   status: "Pending",
  // },
];

export default mockData;
